export const ADD_TOCART = "ADD_TOCART";
export const REMOVE_FROMCART = "REMOVE_FROMCART";
export const SHOW_ALL = "SHOW_ALL";
export const SHOW_CART = "SHOW_CART";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
